# This is a basic workflow to help you get started with Actions

name: build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
