name: semantic-release

on:
  push:
    branches: [main]

jobs:
  semantic:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
      HUSKY: 0
      CI: true
    steps:
      - uses: actions/checkout@v2
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - run: dotnet test
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm i -g @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/github @semantic-release/exec @droidsolutions-oss/semantic-release-nuget @semantic-release/release-notes-generator semantic-release @semantic-release/error
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
          HUSKY: 0
          CI: true
      - run: npx semantic-release --ci
      - run: git push
